# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xlymian-cijoe}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Wanstrath"]
  s.date = %q{2010-02-01}
  s.default_executable = %q{cijoe}
  s.description = %q{CI Joe is a simple Continuous Integration server.}
  s.email = %q{chris@ozmm.org}
  s.executables = ["cijoe"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "bin/cijoe",
     "deps.rip",
     "examples/cijoe.ru",
     "examples/cijoed",
     "lib/cijoe.rb",
     "lib/cijoe/build.rb",
     "lib/cijoe/campfire.rb",
     "lib/cijoe/commit.rb",
     "lib/cijoe/config.rb",
     "lib/cijoe/public/favicon.ico",
     "lib/cijoe/public/octocat.png",
     "lib/cijoe/public/screen.css",
     "lib/cijoe/server.rb",
     "lib/cijoe/talker.rb",
     "lib/cijoe/version.rb",
     "lib/cijoe/views/template.erb",
     "test/helper.rb",
     "test/test_cijoe.rb",
     "test/test_cijoe_server.rb",
     "xlymian-cijoe.gemspec"
  ]
  s.homepage = %q{http://github.com/defunkt/cijoe}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{CI Joe is a simple Continuous Integration server.}
  s.test_files = [
    "test/helper.rb",
     "test/test_cijoe.rb",
     "test/test_cijoe_server.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<choice>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
    else
      s.add_dependency(%q<choice>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
    end
  else
    s.add_dependency(%q<choice>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
  end
end

